config {
  type: "table",
  schema: "curated",
  name: "stg_arco_era5_vertical_profile_vo",
  description: "Cleaned ERA5 vertical profile VO data"
}

SELECT
  SAFE.TIMESTAMP_MICROS(time) AS timestamp_utc,
  DATE(SAFE.TIMESTAMP_MICROS(time)) AS date,
  CAST(hybrid AS FLOAT64) AS hybrid,
  CAST(vo_mean AS FLOAT64) AS vo_mean,
  source_file
FROM ${ref("src_arco_era5_vertical_profile_vo")}
WHERE vo_mean IS NOT NULL