config {
  type: "table",
  schema: "analytics_dev",
  name: "int_orders_enriched",
  tags: ["prod"],
  bigquery: {
    partitionBy: "order_date",
    requirePartitionFilter: true
  }
}

select
  o.order_id,
  o.customer_id,
  o.order_timestamp,
  o.order_date,
  o.amount,

  -- exemple d'enrichissement simple
  case
    when o.amount >= 100 then "high"
    when o.amount >= 50 then "medium"
    else "low"
  end as basket_segment

from ${ref("stg_orders")} o