config {
  type: "view",
  schema: "analytics_dev",
  name: "int_orders_enriched",
  tags: ["intermediate", "prod"]
}

select
  o.order_id,
  o.customer_id,
  o.order_date,
  o.order_amount,

  s.transaction_id,
  s.amount as transaction_amount,

  current_timestamp() as enriched_ts
from ${ref("stg_orders")} o
left join ${ref("stg_sales_transactions")} s
  on s.order_date = o.order_date
  and s.customer_id = o.customer_id