name: Terraform DEV

on:
  push:
    branches: ["main"]
    paths:
      - "terraform/**"
      - ".github/workflows/**"
  pull_request:
    paths:
      - "terraform/**"
      - ".github/workflows/**"
  workflow_dispatch:
    inputs:
      action:
        description: "plan ou apply"
        required: true
        default: "plan"
        type: choice
        options: [plan, apply]

permissions:
  contents: read
  id-token: write

jobs:
  # ---- PLAN sur PR / push
  plan:
    if: ${{ github.event_name != 'workflow_dispatch' }}
    uses: ./.github/workflows/terraform-reusable.yml
    with:
      environment: dev
      action: plan

  # ---- PLAN/APPLY manuel via workflow_dispatch
  manual:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    uses: ./.github/workflows/terraform-reusable.yml
    with:
      environment: dev
      action: ${{ inputs.action }}