name: Terraform STAGING

on:
  pull_request:
    paths:
      - "terraform/**"
      - ".github/workflows/**"
  workflow_dispatch:
    inputs:
      action:
        description: "plan ou apply"
        required: true
        default: "plan"
        type: choice
        options: [plan, apply]

permissions:
  contents: read
  id-token: write

jobs:
  plan:
    if: ${{ github.event_name != 'workflow_dispatch' }}
    uses: ./.github/workflows/terraform-reusable.yml
    with:
      environment: staging
      action: plan

  manual:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    uses: ./.github/workflows/terraform-reusable.yml
    with:
      environment: staging
      action: ${{ inputs.action }}