name: Terraform - DEV

on:
  push:
    branches: ["main"]
    paths:
      - "terraform/**"
      - ".github/workflows/**"

  pull_request:
    paths:
      - "terraform/**"
      - ".github/workflows/**"

  workflow_dispatch:
    inputs:
      action:
        description: "plan or apply"
        required: true
        default: "plan"
        type: choice
        options: [plan, apply]

permissions:
  contents: read
  id-token: write

jobs:
  # ==========================================================
  # 1) PLAN auto (PR + push main)
  # ==========================================================
  plan:
    if: ${{ github.event_name != 'workflow_dispatch' }}
    uses: ./.github/workflows/terraform-reusable.yml
    environment: dev
    with:
      environment: dev
      action: plan
    secrets: inherit

  # ==========================================================
  # 2) Manuel PLAN
  # ==========================================================
  manual_plan:
    if: ${{ github.event_name == 'workflow_dispatch' && inputs.action == 'plan' }}
    uses: ./.github/workflows/terraform-reusable.yml
    environment: dev
    with:
      environment: dev
      action: plan
    secrets: inherit

  # ==========================================================
  # 3) Manuel APPLY (uniquement sur main)
  # ==========================================================
  manual_apply:
    if: ${{ github.event_name == 'workflow_dispatch' && inputs.action == 'apply' && github.ref == 'refs/heads/main' }}
    uses: ./.github/workflows/terraform-reusable.yml
    environment: dev
    with:
      environment: dev
      action: apply
    secrets: inherit