name: Terraform - PROD

on:
  workflow_dispatch:
    inputs:
      action:
        description: "plan or apply"
        required: true
        default: "plan"
        type: choice
        options: [plan, apply]

permissions:
  contents: read
  id-token: write

jobs:
  run:
    uses: ./.github/workflows/terraform-reusable.yml
    with:
      environment: prod
      action: ${{ inputs.action }}
    secrets: inherit